apiVersion: v1
kind: ConfigMap
metadata:
  name: appd
  namespace: upm-ems
  labels:
    config.upm.io/managed: "true"
data:
  config.json: |
    {
      "app": "appD",
      "version": "1",
      "env": "test"
    }
