log:
  level: debug

server:
  port: 8080

nats:
  url: nats://10.255.254.22:30422
  bucket: UPM_CONFIG

bootstrap:
  namespaces:
    - default
    - upm-app
    - upm-ems

reconciler:
  enabled: true
  intervalSeconds: 30

filter:
  managedLabel:
    key: config.upm.io/managed
    value: "true"
