log:
  level: info

server:
  port: 8080

nats:
  url: nats://localhost:4222
  bucket: UPM_CONFIG

watch:
  namespaces:
    - default
  resources:
    - configmaps
    - secrets

filter:
  managedLabel:
    key: config.upm.io/managed
    value: "true"
